name: Monitoring Tools Deployment (Bicep)

trigger: none

variables:
  - group: monitoring-iac

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validation
    displayName: "Validation of IaC templates"
    jobs:
      - job: Workbooks_Validation
        displayName: "Validation of Workbooks templates"
        steps:
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              scriptType: bash
              scriptLocation: inlineScript
              displayName: Workbooks templates validation
              inlineScript: |            
                az deployment group validate \
                --resource-group $(RG_NAME) \
                --template-file $(System.DefaultWorkingDirectory)/monitoring/workbooks.bicep \
                --parameters "{\"workbookSourceId\": {\"value\": \"/subscriptions/$(AZURE_SUBSCRIPTION_ID)/resourceGroups/$(RG_NAME)/providers/Microsoft.Devices/IotHubs/$(IOTHUB_NAME)\"}}" 

      - job: Alerts_Validation
        displayName: "Validation of Alerts templates"
        steps:
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              displayName: Alerts templates validation
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |            
                az deployment group validate \
                --resource-group $(RG_NAME) \
                --template-file $(System.DefaultWorkingDirectory)/monitoring/alerts.bicep \
                --parameters "{\"IotHubs_IoTStarter_iothub_externalid\": {\"value\": \"/subscriptions/$(AZURE_SUBSCRIPTION_ID)/resourceGroups/$(RG_NAME)/providers/Microsoft.Devices/IotHubs/$(IOTHUB_NAME)\"}}" 


  - stage: Deployment
    displayName: "Deployment of IaC templates"
    dependsOn: Validation
    jobs:
      - job: Workbooks_Deployment
        displayName: "Deployment of Workbooks templates"
        steps:
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              scriptType: bash
              scriptLocation: inlineScript
              displayName: Workbooks templates deployment
              inlineScript: |            
                az deployment group create \
                --resource-group $(RG_NAME) \
                --template-file $(System.DefaultWorkingDirectory)/monitoring/workbooks.bicep \
                --parameters "{\"workbookSourceId\": {\"value\": \"/subscriptions/$(AZURE_SUBSCRIPTION_ID)/resourceGroups/$(RG_NAME)/providers/Microsoft.Devices/IotHubs/$(IOTHUB_NAME)\"}}" 

      - job: Alerts_Deployment
        displayName: "Deployment of Alerts templates"
        steps:
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
              displayName: Alerts templates deployment
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |            
                az deployment group create \
                --resource-group $(RG_NAME) \
                --template-file $(System.DefaultWorkingDirectory)/monitoring/alerts.bicep \
                --parameters "{\"IotHubs_IoTStarter_iothub_externalid\": {\"value\": \"/subscriptions/$(AZURE_SUBSCRIPTION_ID)/resourceGroups/$(RG_NAME)/providers/Microsoft.Devices/IotHubs/$(IOTHUB_NAME)\"}}" 
