trigger: none
pr:
  branches:
    include:
    - master

variables:
  - group: ci-cd-common
  - name: MODULE_BUILD_VERSION
    value: "$(Build.BuildId)"

pool:
  vmImage: ubuntu-18.04

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'tests/FilterModuleUnitTest/*.csproj'

- template: tasks/get-acr-creds.yml
  parameters:
    armServiceConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
    acrName: $(ACR_NAME)

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'

